;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AbilityDefinition.StatBuff.BulletArc",DevComment="StatButton buff for bullet arc")
+GameplayTagList=(Tag="AbilityDefinition.StatBuff.BulletDamage",DevComment="StatButton Buff for bullet damage")
+GameplayTagList=(Tag="AbilityDefinition.StatBuff.BulletSpeed",DevComment="StatButton buff for bullet speed")
+GameplayTagList=(Tag="AbilityDefinition.StatBuff.MaxHealth",DevComment="StatButton Buff for Max Health")
+GameplayTagList=(Tag="AbilityDefinition.StatBuff.MovementSpeed",DevComment="Grants stackable movement speed buff for when players purchase a stat button for it.")
+GameplayTagList=(Tag="AbilityDefinition.Test.SuperSpeed",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Jump",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Weapon.PrimaryFire",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Data.BulletImpactDamage",DevComment="The amount of damage a bullet will deal if directly hitting the target.")

